POST /api/2.3/tenders?opt_pretty=1 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 3753
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "tenderPeriod": {
      "endDate": "2017-03-16T17:50:55.851361+02:00"
    }, 
    "title": "Послуги шкільних їдалень", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35
    }, 
    "items": [
      {
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "CPV", 
          "id": "37810000-9", 
          "description": "Test"
        }, 
        "description_en": "Services in school canteens", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "countryName": "Україна", 
          "postalCode": "79000", 
          "region": "м. Київ", 
          "streetAddress": "вул. Банкова 1", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2017-03-05T17:50:55.851203+02:00", 
          "endDate": "2017-04-04T17:50:55.851276+02:00"
        }, 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1
      }, 
      {
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "CPV", 
          "id": "37810000-9", 
          "description": "Test"
        }, 
        "description_en": "Services in school canteens", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "countryName": "Україна", 
          "postalCode": "79000", 
          "region": "м. Київ", 
          "streetAddress": "вул. Банкова 1", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2017-03-05T17:50:55.851310+02:00", 
          "endDate": "2017-04-04T17:50:55.851334+02:00"
        }, 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1
      }
    ], 
    "title_en": "Services in school canteens", 
    "value": {
      "currency": "UAH", 
      "amount": 500
    }, 
    "procurementMethodType": "aboveThresholdTS", 
    "procuringEntity": {
      "kind": "general", 
      "name": "ЗОСШ #10 м.Вінниці", 
      "address": {
        "countryName": "Україна", 
        "postalCode": "21027", 
        "region": "м. Вінниця", 
        "streetAddress": "вул. Стахурського. 22", 
        "locality": "м. Вінниця"
      }, 
      "name_en": "School #10 of Vinnytsia", 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName_en": "The institution \"Secondary school I-III levels № 10 Vinnitsa City Council\"", 
        "id": "21725150", 
        "legalName": "Заклад \"Загальноосвітня школа І-ІІІ ступенів № 10 Вінницької міської ради\""
      }, 
      "contactPoint": {
        "url": "http://sch10.edu.vn.ua/", 
        "name_en": "Kutsa Svitlana V.", 
        "name": "Куца Світлана Валентинівна", 
        "availableLanguage": "uk", 
        "telephone": "+380 (432) 46-53-02"
      }
    }
  }
}

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.3/tenders/bc8d4930816f4bcd928fd98ebc3b6de2
{
  "access": {
    "transfer": "6624da4bb1834019bd87026839ac6543", 
    "token": "ae0954d038ab46cc906295049e76b24e"
  }, 
  "data": {
    "procurementMethod": "open", 
    "complaintPeriod": {
      "startDate": "2017-02-13T17:51:08.427891+02:00", 
      "endDate": "2017-02-13T17:51:12.427891+02:00"
    }, 
    "enquiryPeriod": {
      "startDate": "2017-02-13T17:51:08.427891+02:00", 
      "clarificationsUntil": "2017-03-20T17:50:55.851361+02:00", 
      "endDate": "2017-03-15T17:50:55.851361+02:00"
    }, 
    "submissionMethod": "electronicAuction", 
    "operator": "ua", 
    "next_check": "2017-03-16T17:50:55.851361+02:00", 
    "procuringEntity": {
      "kind": "general", 
      "name": "ЗОСШ #10 м.Вінниці", 
      "address": {
        "postalCode": "21027", 
        "countryName": "Україна", 
        "streetAddress": "вул. Стахурського. 22", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }, 
      "contactPoint": {
        "url": "http://sch10.edu.vn.ua/", 
        "name_en": "Kutsa Svitlana V.", 
        "name": "Куца Світлана Валентинівна", 
        "availableLanguage": "uk", 
        "telephone": "+380 (432) 46-53-02"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName_en": "The institution \"Secondary school I-III levels № 10 Vinnitsa City Council\"", 
        "id": "21725150", 
        "legalName": "Заклад \"Загальноосвітня школа І-ІІІ ступенів № 10 Вінницької міської ради\""
      }, 
      "name_en": "School #10 of Vinnytsia"
    }, 
    "owner": "broker", 
    "title_en": "Services in school canteens", 
    "id": "bc8d4930816f4bcd928fd98ebc3b6de2", 
    "title": "Послуги шкільних їдалень", 
    "tenderID": "R-UA-2017-02-13-000001", 
    "dateModified": "2017-02-13T17:51:08.435093+02:00", 
    "status": "active.tendering", 
    "tenderPeriod": {
      "startDate": "2017-02-13T17:51:08.427891+02:00", 
      "endDate": "2017-03-16T17:50:55.851361+02:00"
    }, 
    "auctionPeriod": {
      "shouldStartAfter": "2017-03-19T00:00:00+02:00"
    }, 
    "procurementMethodType": "aboveThresholdTS", 
    "date": "2017-02-13T17:51:08.428365+02:00", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "items": [
      {
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "CPV", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "description_en": "Services in school canteens", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "countryName": "Україна", 
          "postalCode": "79000", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2017-03-05T17:50:55.851203+02:00", 
          "endDate": "2017-04-04T17:50:55.851276+02:00"
        }, 
        "id": "4b8cde0cc4f6430fbeb7ce2d304a2680", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1
      }, 
      {
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "CPV", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "description_en": "Services in school canteens", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "countryName": "Україна", 
          "postalCode": "79000", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2017-03-05T17:50:55.851310+02:00", 
          "endDate": "2017-04-04T17:50:55.851334+02:00"
        }, 
        "id": "eed1106fda97464ead1802599ff02807", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 500.0, 
      "valueAddedTaxIncluded": true
    }, 
    "awardCriteria": "lowestCost"
  }
}

