PATCH /api/2.3/tenders/634f162a52544f1285269e6c75a350bb/cancellations/455eb0ecb3e8449e99fbe2d674bb3817?acc_token=d36e5cfa2007401ba202822aa162c0d6 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 40
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "reasonType": "unsuccessful"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "pending", 
    "reason": "cancellation reason", 
    "reasonType": "unsuccessful", 
    "date": "2017-02-13T17:51:06.284362+02:00", 
    "cancellationOf": "tender", 
    "id": "455eb0ecb3e8449e99fbe2d674bb3817"
  }
}

